name: Kid Wunders
favicon: null
layout_spectrum: 0.12610876839607954
typography_spectrum: 0.6140862912870944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8016618988476694
  lightness: 0.9364897850900888
  saturation: 0.9127705569844693
  rhythmicContrast: 0.41965353512205184
purpose: []
