name: Kid Wunders
favicon: null
layout_spectrum: 0.2762
typography_spectrum: 0.57053
title: 'Kid Wunders - Play, Learn, Make.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3e93f2'
    - '#050505'
    - '#769b3e'
    - '#aa4481'
  brandStrength: 0.9375
  lightness: 0.9364897850900888
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
